# Generated by Django 6.0.3 on 2026-04-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_route_latitude_route_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='images',
        ),
        migrations.AddField(
            model_name='route',
            name='places',
            field=models.JSONField(blank=True, default=list, verbose_name='Места посещения'),
        ),
    ]
