# Generated by Django 6.0.3 on 2026-04-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_remove_route_images_route_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='location',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка на 2ГИС карту'),
        ),
    ]
