# Generated by Django 6.0.3 on 2026-04-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_route_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='location',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка на карту'),
        ),
    ]
