# Generated by Django 6.0.3 on 2026-04-21 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_alter_route_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='routes/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='routes.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Изображение маршрута',
                'verbose_name_plural': 'Изображения маршрутов',
                'ordering': ['order'],
            },
        ),
    ]
