# Generated by Django 6.0.3 on 2026-04-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0009_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='end_city',
            field=models.CharField(blank=True, max_length=200, verbose_name='Город назначения'),
        ),
        migrations.AddField(
            model_name='route',
            name='start_city',
            field=models.CharField(blank=True, max_length=200, verbose_name='Город отправления'),
        ),
        migrations.AddField(
            model_name='route',
            name='waypoints',
            field=models.CharField(blank=True, max_length=500, verbose_name='Промежуточные точки'),
        ),
    ]
