# Generated by Django 6.0.3 on 2026-04-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0010_route_end_city_route_start_city_route_waypoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='city',
            field=models.CharField(blank=True, max_length=200, verbose_name='Город для карты'),
        ),
    ]
