# Generated by Django 5.2.12 on 2026-04-28 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0011_route_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='routes.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Комментарий к маршруту',
                'verbose_name_plural': 'Комментарии к маршрутам',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='routes.route', verbose_name='Маршрут')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лайк маршрута',
                'verbose_name_plural': 'Лайки маршрутов',
                'unique_together': {('route', 'user')},
            },
        ),
    ]
